### ISSUE TITLE
Deprecating unit conversion utilities posted 9/28/2022

### ISSUE THREAD

**Issue by ktn7419** [pilotak/homeassistant-clientraw#20]
Home Assistant Core 2022.10 now gives a Warning now...
 "Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 285: temperature = convert_temperature(
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 298: temperature = convert_temperature(
Detected integration that uses pressure utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.PressureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 381: pressure = round(convert_pressure(
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 439: temperature = convert_temperature("

Just a warning for now, but it says you need to use the "corresponding static classes from homeassistant/util/unit_conversion"

They don't show any examples on how to migrate to the new utilities. :o(

**Comment by pilotak** [comment]
Oh dear, at least it's only warning. I will look at it through out autumn.

**Comment by quemart** [comment]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 12:02:51 (28 occurrences)
Last logged: 12:02:51

Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 259: if not self.hass.config.units.is_metric:
Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 379: if not self.hass.config.units.is_metric:
Detected integration that uses pressure utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.PressureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 380: pressure = round(convert_pressure(
Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 424: if not self.hass.config.units.is_metric:
Detected integration that uses distance utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.DistanceConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 425: height = convert_distance(

I started getting this today, don't know if anyone else has seen it.

**Comment by ktn7419** [comment]
Yes, also have received. Probably related to the one I reported.

**Comment by vk2him** [comment]
The fix for the  ```is_metric``` issue is documented here:

https://developers.home-assistant.io/blog/2022/10/14/deprecate-unit-system/

**Comment by pilotak** [comment]
PR is here! #21

**Comment by vk2him** [comment]
PR #21 has fixed the ```is_metric``` errors for me - thanks!

**Comment by pilotak** [comment]
#21 merged

**Comment by ktn7419** [comment]
I update in Home Assistance and now see this one in the log:
"Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 285: temperature = convert_temperature(
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 298: temperature = convert_temperature(
Detected integration that uses pressure utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.PressureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 381: pressure = round(convert_pressure(
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 439: temperature = convert_temperature("

Looks like a new issue?
